address: https://test-stand.gb.ru/gateway/login 
username: Joel1981
password: 3821fc40bb
address2: https://test-stand.gb.ru/api/posts
titlee: Post title
descriptionn: Post description
contentt: Post content